//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMainService")]
    public interface IMainService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/ComputeNumber", ReplyAction="http://tempuri.org/IMainService/ComputeNumberResponse")]
        System.Threading.Tasks.Task<string> ComputeNumberAsync(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/GetNumbers", ReplyAction="http://tempuri.org/IMainService/GetNumbersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetNumbersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface IMainServiceChannel : ServiceReference1.IMainService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class MainServiceClient : System.ServiceModel.ClientBase<ServiceReference1.IMainService>, ServiceReference1.IMainService
    {
        
        public MainServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> ComputeNumberAsync(string input)
        {
            return base.Channel.ComputeNumberAsync(input);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetNumbersAsync()
        {
            return base.Channel.GetNumbersAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
